export const NODE_TYPES = {
  startTrigger: {
    key: 'startTrigger',
    label: 'Start / Trigger',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#16a34a',
    icon: 'Play',
    description: 'Entry point or triggering event',
    defaultData: {
      label: 'Start',
      nodeType: 'startTrigger',
      owner: '',
      purpose: 'Initiates the workflow',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'manual',
      riskTag: 'low',
      humanApprovalRequired: false,
      monitoringEnabled: false,
      loggingEnabled: false,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 0 },
  },
  aiAction: {
    key: 'aiAction',
    label: 'AI Action',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#7c3aed',
    icon: 'BrainCircuit',
    description: 'AI-driven processing or analysis',
    defaultData: {
      label: 'AI Action',
      nodeType: 'aiAction',
      owner: '',
      purpose: '',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'supervised',
      riskTag: 'medium',
      humanApprovalRequired: false,
      monitoringEnabled: false,
      loggingEnabled: false,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 1 },
  },
  humanReview: {
    key: 'humanReview',
    label: 'Human Review',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#ea580c',
    icon: 'UserCheck',
    description: 'Human oversight or approval checkpoint',
    defaultData: {
      label: 'Human Review',
      nodeType: 'humanReview',
      owner: '',
      purpose: 'Review and approve AI output',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'manual',
      riskTag: 'low',
      humanApprovalRequired: true,
      monitoringEnabled: false,
      loggingEnabled: true,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 1 },
  },
  decisionGate: {
    key: 'decisionGate',
    label: 'Decision / Gate',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#ca8a04',
    icon: 'GitBranch',
    description: 'Conditional branching or routing',
    defaultData: {
      label: 'Decision',
      nodeType: 'decisionGate',
      owner: '',
      purpose: '',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'supervised',
      riskTag: 'medium',
      humanApprovalRequired: false,
      monitoringEnabled: false,
      loggingEnabled: false,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 2, targets: 1 },
  },
  dataAccess: {
    key: 'dataAccess',
    label: 'Data Access',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#0891b2',
    icon: 'Database',
    description: 'Read or write to a data source',
    defaultData: {
      label: 'Data Access',
      nodeType: 'dataAccess',
      owner: '',
      purpose: '',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'supervised',
      riskTag: 'medium',
      humanApprovalRequired: false,
      monitoringEnabled: false,
      loggingEnabled: false,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 1 },
  },
  monitoringLogging: {
    key: 'monitoringLogging',
    label: 'Monitoring / Logging',
    color: '#6b7280',
    bgColor: '#f9fafb',
    borderColor: '#4b5563',
    icon: 'Activity',
    description: 'Audit trail or performance monitoring',
    defaultData: {
      label: 'Monitor & Log',
      nodeType: 'monitoringLogging',
      owner: '',
      purpose: 'Record actions and metrics for audit',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'full',
      riskTag: 'low',
      humanApprovalRequired: false,
      monitoringEnabled: true,
      loggingEnabled: true,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 1 },
  },
  escalation: {
    key: 'escalation',
    label: 'Escalation',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#dc2626',
    icon: 'AlertTriangle',
    description: 'Route to higher authority',
    defaultData: {
      label: 'Escalate',
      nodeType: 'escalation',
      owner: '',
      purpose: 'Escalate to senior authority',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'manual',
      riskTag: 'high',
      humanApprovalRequired: true,
      monitoringEnabled: true,
      loggingEnabled: true,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 1, targets: 1 },
  },
  stopRollback: {
    key: 'stopRollback',
    label: 'Stop / Rollback',
    color: '#991b1b',
    bgColor: '#fef2f2',
    borderColor: '#7f1d1d',
    icon: 'RotateCcw',
    description: 'Halt and optionally revert changes',
    defaultData: {
      label: 'Stop / Rollback',
      nodeType: 'stopRollback',
      owner: '',
      purpose: 'Halt and revert if needed',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'manual',
      riskTag: 'critical',
      humanApprovalRequired: true,
      monitoringEnabled: true,
      loggingEnabled: true,
      escalationDestination: '',
      rollbackAvailable: true,
    },
    handleConfig: { sources: 0, targets: 1 },
  },
  outputEnd: {
    key: 'outputEnd',
    label: 'Output / End',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#16a34a',
    icon: 'CheckCircle',
    description: 'Final output or workflow completion',
    defaultData: {
      label: 'Output / End',
      nodeType: 'outputEnd',
      owner: '',
      purpose: 'Deliver final output',
      inputDescription: '',
      outputDescription: '',
      datasetIds: [],
      autonomyLevel: 'supervised',
      riskTag: 'low',
      humanApprovalRequired: false,
      monitoringEnabled: false,
      loggingEnabled: false,
      escalationDestination: '',
      rollbackAvailable: false,
    },
    handleConfig: { sources: 0, targets: 1 },
  },
};

export const NODE_TYPE_KEYS = Object.keys(NODE_TYPES);
